#!/bin/bash

jshint $(git diff --cached --name-only --diff-filter=AM | egrep '.js$' | grep -v compat.js) --verbose &&
jscs   $(git diff --cached --name-only --diff-filter=AM | egrep '.js$' | grep -v compat.js) &&
exit 0

exit 1